apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: cloudops-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: slack-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: webhookURL
      remoteRef:
        key: cloudops/slack-webhook
  
