apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: cloudops-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cloudops-prod
  selector:
    matchLabels:
     app.kubernetes.io/name: prometheus-redis-exporter
  endpoints:
    - port: redis-exporter
      path: /metrics
      interval: 15s