apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudops-api
  namespace: cloudops-monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cloudops-prod
  selector:
    matchLabels:
      app: cloudops-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s