apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Suraj8853/cloudops-gitops.git
    targetRevision: HEAD
    path: manifests/policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
